Repository impresso/impresso-frontend, pull requests merged in 2019-07, with the labels that each got.

#358 homepage
  package.json
  src/assets/homepage.json
  src/assets/img/newspapers_bg_dark.jpg
  src/assets/img/newspapers_bg_dark_blue.jpg
  src/assets/img/newspapers_bg_light.jpg
  src/components/Autocomplete.vue
  src/components/HomePage.vue
  src/components/HomePageFaq.vue
  src/components/HomePageFooter.vue
  src/components/HomePageMessages.vue
  src/components/HomePageRecipes.vue
  src/components/HomePageSplash.vue
Labels: enhancement

#361 removed suggestion-side class
  src/components/Autocomplete.vue
Labels: bug, design

#359 removed check for article type 'ar' because we always want to display the iiif image
  src/components/modules/SearchResultsListItem.vue
Labels: bug

#362 removed auth for routes that are publicly available
  src/router/index.js
Labels: enhancement

#366 fixed bug with keyboard/Enter
  src/components/Autocomplete.vue
Labels: bug

#364 remove visible iiif link
  src/components/modules/SearchResultsListItem.vue
Labels: bug

#371 added message to homepage and close method
  src/assets/homepage.json
  src/components/HomePage.vue
  src/components/HomePageFaq.vue
  src/components/HomePageFooter.vue
  src/components/HomePageMessages.vue
  src/components/HomePageRecipes.vue
  src/components/HomePageSplash.vue
Labels: enhancement

#377 fixed typo
  src/assets/homepage.json
Labels: bug
