Repository impresso/impresso-frontend, pull requests merged in 2019-03, with the labels that each got.

#248 added markdown-decorate for classes in md, and enabled html in md
  package.json
  src/filters/markdown.js
Labels: enhancement

#249 added translation
  src/i18n/messages.js
Labels: enhancement

#257 added check to find if issue contains pages or throw console.error
  src/components/IssuePage.vue
Labels: enhancement

#259 Search/filter pills
  src/components/Autocomplete.vue
  src/components/modules/FilterLanguage.vue
  src/components/modules/FilterNewspaper.vue
  src/components/modules/FilterRegex.vue
  src/components/modules/FilterTopic.vue
  src/components/modules/FilterWrapper.vue
Labels: UX, design

#256 Search/bulk collection naming
  src/components/SearchPage.vue
Labels: UX, enhancement

#245 simplified facet filters and added 'exclude' option on facet mouseover
  src/components/SearchFacets.vue
  src/components/modules/FacetLanguage.vue
  src/components/modules/FacetNewspaper.vue
  src/components/modules/FacetTopic.vue
Labels: enhancement

#271 #100 - fix drag, zoom and overlay issue on IssueViewer
  src/components/IssuePage.vue
Labels: bug, enhancement

#273 minor improvements
  src/components/IssuePage.vue
  src/components/modules/CollectionAddTo.vue
Labels: enhancement

#269 Download csv
  src/components/SearchPage.vue
  src/components/TheHeader.vue
  src/components/modules/Toast.vue
  src/i18n/dateTimeFormats.js
  src/services/index.js
  src/store/Jobs.js
  src/store/Search.js
  src/store/index.js
Labels: feature, good first issue
